### ISSUE TITLE
Problem of working with laravel-elixir-useref

### ISSUE THREAD

**Issue by jaceju** [FabioAntunes/laravel-elixir-wiredep#2]
Wrong path of bower_component be fixed by `asset` function in #1, but it introduces new bug with [laravel-elixir-useref](https://www.npmjs.com/package/laravel-elixir-useref). Consider the example:

``` html
    @if (Config::get('app.debug'))
        <!-- build:css(public) css/vendor.css -->
        <!-- bower:css -->
        <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.css') }}" />
        <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.css') }}" />
        <!-- endbower -->
        <!-- endbuild -->
    @else
        <link rel="stylesheet" href="{{ elixir("css/vendor.css") }}">
    @endif
```

This would not generate the `css/vendor.css` because they are not parsable path with `asset` function.

Any idea?

**Comment by FabioAntunes** [comment]
Hmmm I didn't know that this package was being used combined with laravel-elixir-useref.
I'm looking at source code of laravel-elixir-useref, the only way is applying a filter on the assets stream removing the extra markup generated by the asset() function

**Comment by jaceju** [comment]
@FabioAntunes: Maybe you can try my solution in #1?

**Comment by FabioAntunes** [comment]
@jaceju yeah, I didn't notice your suggestion sorry about that, it's the best solution thanks for the tip.

**Comment by jaceju** [comment]
@FabioAntunes Thank you for this change.

**Comment by FDiskas** [comment]
I did a pull request to https://github.com/jonkemp/useref/pull/7
The main idea is to match assets no matter in what syntax they are. Here is an example http://regexr.com/3d2r8
If this pull request will be accepted then it could be posible to use `asset()` or `elixir()` in template.
So please vote for this.
And I think that this https://github.com/FabioAntunes/laravel-elixir-wiredep/commit/c1a54352d15d865f8fddd9ca40b00eb1397dd2f9 commit must be reverted - because this is special for laravel and assets should be used with `asset()` or `elixir()`
